version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: apk install openjdk14-jre || apt-get install openjdk14-jre || dnf install openjdk14-jre
            - run: npm install
            - run: npm run make-cypher
            - run: npm run build
            - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            - run: npm publish
              
workflows:
    build-and-publish:
      jobs:
        - build-and-publish
